/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.view;

import org.example.controller.CadastrarClienteController;

/**
 *
 * @author Joao
 */
public class JMainView extends javax.swing.JFrame {

    /**
     * Creates new form JmainView2
     */
    public JMainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tela = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuControlarEstacionamentos = new javax.swing.JMenu();
        menuCadastrarEstacionamentos = new javax.swing.JMenuItem();
        menuListarEstacionamentos = new javax.swing.JMenuItem();
        menuValores = new javax.swing.JMenuItem();
        menuEstacionarVeiculo = new javax.swing.JMenuItem();
        menuLiberarVaga = new javax.swing.JMenuItem();
        menuControlarClientes = new javax.swing.JMenu();
        menuCadastrarClientes = new javax.swing.JMenuItem();
        menuHistoricoCliente = new javax.swing.JMenuItem();
        menuCadastrarVeiculo = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela principal");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Bem Vindo Usuário!");

        tela.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout telaLayout = new javax.swing.GroupLayout(tela);
        tela.setLayout(telaLayout);
        telaLayout.setHorizontalGroup(
            telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel1)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        telaLayout.setVerticalGroup(
            telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaLayout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel1)
                .addContainerGap(288, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tela)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tela, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        menuControlarEstacionamentos.setText("Controlar Estacionamentos");
        menuControlarEstacionamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuControlarEstacionamentosMouseClicked(evt);
            }
        });
        menuControlarEstacionamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuControlarEstacionamentosActionPerformed(evt);
            }
        });

        menuCadastrarEstacionamentos.setText("Cadastrar estacionamentos");
        menuCadastrarEstacionamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarEstacionamentosActionPerformed(evt);
            }
        });
        menuControlarEstacionamentos.add(menuCadastrarEstacionamentos);

        menuListarEstacionamentos.setText("Listar estacionamentos");
        menuListarEstacionamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListarEstacionamentosActionPerformed(evt);
            }
        });
        menuControlarEstacionamentos.add(menuListarEstacionamentos);

        menuValores.setText("Valores");
        menuControlarEstacionamentos.add(menuValores);

        menuEstacionarVeiculo.setText("Estacionar veículo");
        menuEstacionarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEstacionarVeiculoActionPerformed(evt);
            }
        });
        menuControlarEstacionamentos.add(menuEstacionarVeiculo);

        menuLiberarVaga.setText("Liberar vaga");
        menuControlarEstacionamentos.add(menuLiberarVaga);

        jMenuBar1.add(menuControlarEstacionamentos);

        menuControlarClientes.setText("Controlar clientes");

        menuCadastrarClientes.setText("Cadastrar clientes");
        menuControlarClientes.add(menuCadastrarClientes);

        menuHistoricoCliente.setText("Histórico cliente");
        menuControlarClientes.add(menuHistoricoCliente);

        menuCadastrarVeiculo.setText("Cadastrar veículo");
        menuCadastrarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarVeiculoActionPerformed(evt);
            }
        });
        menuControlarClientes.add(menuCadastrarVeiculo);

        jMenuBar1.add(menuControlarClientes);

        menuSobre.setText("Sobre");

        jMenuItem5.setText("Sobre nós");
        menuSobre.add(jMenuItem5);

        jMenuBar1.add(menuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuControlarEstacionamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuControlarEstacionamentosActionPerformed
     
    }//GEN-LAST:event_menuControlarEstacionamentosActionPerformed

    private void menuControlarEstacionamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuControlarEstacionamentosMouseClicked
        //CadastrarClienteView aaaaa = new CadastrarClienteView();
        // tela.add(aaaaa);
        // aaaaa.setVisible(true);
    }//GEN-LAST:event_menuControlarEstacionamentosMouseClicked

    private void menuCadastrarEstacionamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarEstacionamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadastrarEstacionamentosActionPerformed

    private void menuCadastrarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadastrarVeiculoActionPerformed

    private void menuEstacionarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEstacionarVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuEstacionarVeiculoActionPerformed

    private void menuListarEstacionamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarEstacionamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuListarEstacionamentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JMainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuCadastrarClientes;
    private javax.swing.JMenuItem menuCadastrarEstacionamentos;
    private javax.swing.JMenuItem menuCadastrarVeiculo;
    private javax.swing.JMenu menuControlarClientes;
    private javax.swing.JMenu menuControlarEstacionamentos;
    private javax.swing.JMenuItem menuEstacionarVeiculo;
    private javax.swing.JMenuItem menuHistoricoCliente;
    private javax.swing.JMenuItem menuLiberarVaga;
    private javax.swing.JMenuItem menuListarEstacionamentos;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JMenuItem menuValores;
    private javax.swing.JDesktopPane tela;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JMenuItem getMenuCadastrarCliente() {
    return menuCadastrarClientes;
    }
    
    public javax.swing.JMenuItem getMenuCadastrarVeiculo() {
        return menuCadastrarVeiculo;
    }

    public javax.swing.JMenuItem getMenuCadastrarEstacionamento() {
    return menuCadastrarEstacionamentos;
    }

    public javax.swing.JMenuItem getMenuEstacionarVeiculo() {
    return menuEstacionarVeiculo;
    }

    public javax.swing.JMenuItem getMenuHistoricoCliente() {
    return menuHistoricoCliente;
    }

    public javax.swing.JMenuItem getMenuLiberarVaga() {
    return menuLiberarVaga;
    }

    public javax.swing.JMenuItem getMenuListarEstacionamentos() {
    return menuListarEstacionamentos;
    }

    public javax.swing.JMenuItem getMenuValores() {
    return menuValores;
    }
    public javax.swing.JDesktopPane getTela() {
        return tela;
    }
}


