/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.view;

/**
 *
 * @author Joao
 */
public class JMainView extends javax.swing.JFrame {

    /**
     * Creates new form JMain
     */
    public JMainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnHistoricoCliente = new javax.swing.JButton();
        btnValores = new javax.swing.JButton();
        btnListarEstacionamentos = new javax.swing.JButton();
        btnLiberarVaga = new javax.swing.JButton();
        btnEstacionarVeiculo = new javax.swing.JButton();
        btnCadastrarCliente = new javax.swing.JButton();
        btnCadastrarEstacionamento = new javax.swing.JButton();
        btnCadastrarVeiculo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Estacionamento Java Parkings");

        btnHistoricoCliente.setText("Histórico cliente");
        btnHistoricoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoricoClienteActionPerformed(evt);
            }
        });

        btnValores.setText("Valores");
        btnValores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValoresActionPerformed(evt);
            }
        });

        btnListarEstacionamentos.setText("Listar estacionamentos");
        btnListarEstacionamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarEstacionamentosActionPerformed(evt);
            }
        });

        btnLiberarVaga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLiberarVaga.setText("Liberar vaga");
        btnLiberarVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiberarVagaActionPerformed(evt);
            }
        });

        btnEstacionarVeiculo.setText("Estacionar veículo");
        btnEstacionarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstacionarVeiculoActionPerformed(evt);
            }
        });

        btnCadastrarCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCadastrarCliente.setText("Cadastrar cliente");
        btnCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarClienteActionPerformed(evt);
            }
        });

        btnCadastrarEstacionamento.setText("Cadastrar estacionamento");
        btnCadastrarEstacionamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarEstacionamentoActionPerformed(evt);
            }
        });

        btnCadastrarVeiculo.setText("Cadastrar veículo");
        btnCadastrarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarVeiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnValores, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(btnHistoricoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(btnEstacionarVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(btnLiberarVaga, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(btnCadastrarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(btnListarEstacionamentos, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(btnCadastrarEstacionamento, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(btnCadastrarVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarEstacionamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLiberarVaga, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEstacionarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnListarEstacionamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHistoricoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnValores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnValoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValoresActionPerformed
        PerguntaEstacionamentoView tlm = new PerguntaEstacionamentoView(this, true);
        tlm.getBtnVoltar().addActionListener(evento -> {
            tlm.dispose();
        });
        tlm.getBtnProsseguir().addActionListener(evento -> {
        tlm.dispose();
        ValoresView tela = new ValoresView(this, true);
        tela.setVisible(true);
        });
        tlm.setVisible(true);
    }//GEN-LAST:event_btnValoresActionPerformed

    private void btnCadastrarEstacionamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarEstacionamentoActionPerformed
       //tem que passar isso pro controller
        CadastrarEstacionamentoView tela = new CadastrarEstacionamentoView(this, true);
        tela.setVisible(true);
        
    }//GEN-LAST:event_btnCadastrarEstacionamentoActionPerformed

    private void btnCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarClienteActionPerformed

    }//GEN-LAST:event_btnCadastrarClienteActionPerformed

    private void btnLiberarVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiberarVagaActionPerformed
        LiberarVagaView tela = new LiberarVagaView(this, true);
        tela.setVisible(true);
    }//GEN-LAST:event_btnLiberarVagaActionPerformed

    private void btnEstacionarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstacionarVeiculoActionPerformed
        EstacionarVeiculoView tela = new EstacionarVeiculoView(this, true);
        tela.setVisible(true);
    }//GEN-LAST:event_btnEstacionarVeiculoActionPerformed

    private void btnListarEstacionamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarEstacionamentosActionPerformed
        ListarEstacionamentosView tela = new ListarEstacionamentosView(this, true);
        tela.setVisible(true);
    }//GEN-LAST:event_btnListarEstacionamentosActionPerformed

    private void btnHistoricoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoricoClienteActionPerformed
        PerguntaCpfView tlm = new PerguntaCpfView(this, true);
        tlm.getBtnVoltar().addActionListener(evento -> {
            tlm.dispose();
        });
        tlm.getBtnProsseguir().addActionListener(evento -> {
        tlm.dispose();
        HistoricoClienteView tela = new HistoricoClienteView(this, true);
        tela.setVisible(true);
        });
        tlm.setVisible(true);
    }//GEN-LAST:event_btnHistoricoClienteActionPerformed

    private void btnCadastrarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarVeiculoActionPerformed
        
    }//GEN-LAST:event_btnCadastrarVeiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JMainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarCliente;
    private javax.swing.JButton btnCadastrarEstacionamento;
    private javax.swing.JButton btnCadastrarVeiculo;
    private javax.swing.JButton btnEstacionarVeiculo;
    private javax.swing.JButton btnHistoricoCliente;
    private javax.swing.JButton btnLiberarVaga;
    private javax.swing.JButton btnListarEstacionamentos;
    private javax.swing.JButton btnValores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnCadastrarCliente() {
    return btnCadastrarCliente;
    }
    
    public javax.swing.JButton getBtnCadastrarVeiculo() {
        return btnCadastrarVeiculo;
    }

    public javax.swing.JButton getBtnCadastrarEstacionamento() {
    return btnCadastrarEstacionamento;
    }

    public javax.swing.JButton getBtnEstacionarVeiculo() {
    return btnEstacionarVeiculo;
    }

    public javax.swing.JButton getBtnHistoricoCliente() {
    return btnHistoricoCliente;
    }

    public javax.swing.JButton getBtnLiberarVaga() {
    return btnLiberarVaga;
    }

    public javax.swing.JButton getBtnListarEstacionamentos() {
    return btnListarEstacionamentos;
    }

    public javax.swing.JButton getBtnValores() {
    return btnValores;
    }
}
